### PR TITLE
Add About page

### PR DESCRIPTION
**Pull request by n3a9**

### CODE REVIEW

**Comment by firebolt55439** [comment]
I took a look — I don't see any changes that should break anything. Looks good to me.

**Comment by firebolt55439** [comment]
You're good to merge whenever you'd like.

**Comment by n3a9** [comment]
Just formalizing process a little more :)

**Comment by firebolt55439** [comment]
I'll run my changes by you in the future as well in the form of pull requests — this review system is actually pretty cool.

**Pull request merged**
